table Date2
	lineageTag: 6ed3590a-3926-498a-938f-5dc02eef127b

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: f8d9629e-a7f0-47c9-9470-b228d2356d82
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3c201c74-9268-4415-b537-c2fdd6d3d628
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Month
		dataType: string
		lineageTag: d9b2b176-c19e-49ce-b0fb-6aae200a6337
		summarizeBy: none
		sourceColumn: Month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition Date2 = m
		mode: import
		queryGroup: DIM\Dates
		source =
				let
				    Source = Date,
				    #"Autres colonnes supprimées" = Table.SelectColumns(Source,{"DateKey", "Date", "Month"})
				in
				    #"Autres colonnes supprimées"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

